import { BASE_BLUEROV } from './base'

const SERVOS_HEAVY = {
  SERVO7_FUNCTION: 39, // Motor7
  SERVO8_FUNCTION: 40, // Motor8
  SERVO8_REVERSED: 0,
  SERVO9_FUNCTION: 59, // RCIN9 (camera)
  SERVO10_FUNCTION: 7, // mount_tilt
  SERVO10_REVERSED: 1,
}

const BLUEROV2_HEAVY = {
  ...BASE_BLUEROV,
  ATC_ANG_PIT_P: 6.0,
  ATC_ANG_RLL_P: 6.0,
  ATC_ANG_YAW_P: 6.0,
  FRAME_CONFIG: 2,
}